- name: change hostname
  hostname:
    name: '{{ hostname }}'

- name: update all packages to the latest version
  apt:
    upgrade: dist

- name: remove useless packages from the cache
  apt:
    autoclean: yes

- name: remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: restart server
  become: yes
  shell: sleep 2 && /sbin/shutdown -r now "system package upgraded"
  async: 1
  poll: 0

- name: waiting 60 secs for server to come back
  become: false
  local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 state=started delay=60 timeout=120
