- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: latest

- name: install ca-certifiactes
  apt:
    name: ca-certificates
    state: latest

- name: install curl
  apt: 
    name: curl
    state: latest

- name: install software-properties-common
  apt: 
    name: software-properties-common
    state: latest

- name: add Docker's official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
   
- name: add repository
  shell: sudo add-apt-repository \
   "deb [arch=armhf] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

- name:  install docker
  apt:
    name: docker-ce
    update_cache: true

